#!/usr/bin/bash

#SBATCH -J job_name
#SBATCH -o SLURM.log
#SBATCH -e ERROR.err
#SBATCH -t 10:00:00
#SBATCH --mail-user=isak.e.lindhe@gmail.com
#SBATCH --mail-type=ALL

date
# CBF_ROOT=/data/staff/common/ML-crystals/real_cbf
CBF_ROOT=/mnt/staff/common/ML-crystals/real_cbf
OUT=out


mkdir $OUT

for date in $CBF_ROOT/*; do
    for sample in $CBF_ROOT/*; do
        for scan in $sample/*; do
            for cbf in $scan/*; do
                FNAME=$(echo $cbf | sed 's/\//__/g' | sed 's/.cbf$//' | cut -d'_' -f16-)
                distl.signal_strength "$cbf" > "$OUT/$FNAME"
            done
        done
    done
done
date

