#!/usr/bin/bash

#SBATCH -J job_name
#SBATCH -o SLURM.log
#SBATCH -e ERROR.err

date
# CBF_ROOT=/data/staff/common/ML-crystals/real_cbf
CBF_ROOT=/mnt/staff/common/ML-crystals/real_cbf

for sample in $CBF_ROOT/*; do
	for scan in $sample/*; do
		for cbf in $scan/*; do
			COUNT=$(distl.signal_strength "$cbf" | grep "Spot Total" | awk '{print $4}') && echo "$cbf,$COUNT"
		done
	done
done
date

